config/routes.rb
Rails.application.routes.draw do
  get "oauths/oauth"
  get "oauths/callback"
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  get "plans/destroy"
  root "static_pages#top"
  resources :users, only: %i[new create]
  resources :books, only: %i[index new create show edit update destroy] do
    resources :plans, only: %i[destroy]
    collection do
      get :bookmarks
    end
  end
  resources :bookmarks, only: %i[create destroy]
  resource :profile, only: %i[show edit update]
  resources :password_resets, only: %i[new create edit update]
  resources :contacts, only: %i[new create]

  get "login", to: "user_sessions#new"
  post "login", to: "user_sessions#create"
  delete "logout", to: "user_sessions#destroy"
  get "created_book", to: "books#created_index"
  get "terms", to: "static_pages#terms"
  get "privacy", to: "static_pages#privacy"
  post "oauth/callback", to: "oauths#callback"
  get "oauth/callback", to: "oauths#callback"
  get "oauth/:provider", to: "oauths#oauth", as: :auth_at_provider
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/authentication.rb
class Authentication < ApplicationRecord
  belongs_to :user
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true, length: { maximum: 255 }
  validates :outline_title, length: { maximum: 255 }
  validates :outline_body, length: { maximum: 65_535 }
  validates :is_public, inclusion: { in: [ true, false ] }

  belongs_to :user
  has_many :plans, dependent: :destroy
  has_many :bookmarks, dependent: :destroy

  accepts_nested_attributes_for :plans, allow_destroy: true

  BACKGROUND_IMAGES = %w[blue.jpg brown.jpg green.jpg orange.jpg pink.jpg purple.jpg red.jpg yellow.jpg].freeze

  validates :image, inclusion: { in: BACKGROUND_IMAGES }
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :user_id, uniqueness: { scope: :book_id }
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :email, presence: true
  validates :message, presence: true
end

app/models/plan.rb
class Plan < ApplicationRecord
  validates :title, length: { maximum: 255 }
  validates :location, length: { maximum: 255 }
  validates :detail, length: { maximum: 65_535 }
  validates :memo, length: { maximum: 65_535 }
  validates :cost_display_per, inclusion: { in: [ true, false ] }, allow_nil: true
  validates :cost_display_total, inclusion: { in: [ true, false ] }, allow_nil: true

  belongs_to :book
  geocoded_by :location
  after_validation :geocode
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  has_many :books, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :bookmark_books, through: :bookmarks, source: :book
  has_many :authentications, dependent: :destroy
  accepts_nested_attributes_for :authentications

  validates :password, length: { minimum: 8 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }
  validates :email, presence: true, uniqueness: true
  validates :reset_password_token, uniqueness: true, allow_nil: true

  enum gender: { male: 0, female: 1, other: 2 }
  enum age_group: { under19: 0, twenties: 1, thirties: 2, fourties: 3, fifties: 4, over60: 5 }

  def own?(object)
    self.id == object.user_id
  end

  def bookmark(book)
    bookmark_books << book
  end

  def unbookmark(book)
    bookmark_books.destroy(book)
  end

  def bookmark?(book)
    bookmark_books.include?(book)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  skip_before_action :require_login, only: %i[index show]

  def index
    @books = Book.where(is_public: true).page(params[:page]).per(15)
  end

  def new
    @book = Book.new
  end

  def create
    @book = current_user.books.build(book_params)
    if @book.save
      redirect_to book_path(@book), success: t("books.create.success")
    else
      flash.now[:danger] = t("books.create.failure")
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @book = Book.find(params[:id])
    @plans = Plan.find_by(book_id: params[:id])
  end

  def edit
    @book = current_user.books.find(params[:id])
  end

  def update
    @book = current_user.books.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), success: t("books.update.success")
    else
      flash.now[:danger] = t("books.update.failure")
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    book = current_user.books.find(params[:id])
    book.destroy!
    redirect_to books_path, success: t("books.destroy.success"), status: :see_other
  end

  def created_index
    @books = Book.where(user_id: current_user.id).page(params[:page]).per(15)
  end

  def bookmarks
    @bookmark_books = current_user.bookmark_books.includes(:user)
  end

  private

  def book_params
    params.require(:book).permit(
      :title, :outline_title, :outline_body, :is_public, :image,
      plans_attributes: [ :id, :date, :title, :start_time, :end_time, :icon, :location, :location_url, :detail, :memo, :cost, :cost_display_per, :cost_display_total, :_destroy, :latitude, :longitude ]
      )
  end
end

app/controllers/oauths_controller.rb
class OauthsController < ApplicationController
  skip_before_action :require_login

  def oauth
    login_at(auth_params[:provider])
  end

  def callback
    provider = auth_params[:provider]
    status = auth_params[:status]
    Rails.logger.debug "#{status}"
    if @user = login_from(provider)
      redirect_to root_path, notice: "#{provider.titleize}でログインしました"
    else
      begin
        @user = create_from(provider)
        reset_session
        auto_login(@user)
        redirect_to root_path, notice: "#{provider.titleize}でログインしました"
      rescue
        # flash.now[:danger] = "#{provider.titleize}でログインできませんでした"
        # render :new, status: :unprocessable_entity
        redirect_to root_path, notice: "#{provider.titleize}でログインできませんでした"
      end
    end
  end

  private

  def auth_params
    params.permit(:code, :provider, :error, :state)
  end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action :set_book

  def destroy
    @plan = @book.plans.find(params[:id])
    @plan.destroy
    redirect_to edit_book_path(@book)
  end

  private

  def set_book
    @book = current_user.books.find(params[:book_id])
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_user, only: %i[edit update]

  def edit; end

  def update
    if @user.update(user_params)
      redirect_to profile_path, success: "登録情報を更新しました"
    else
      flash.now["danger"] = "登録情報を更新できませんでした"
      render :edit, status: :unprocessable_entity
    end
  end

  def show; end

private

  def set_user
    @user = User.find(current_user.id)
  end

  def user_params
    params.require(:user).permit(:email, :gender, :age_group, :password, :password_confirmation)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: %i[new create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      auto_login(@user)
      redirect_to root_path, success: t("users.create.success")
    else
      flash.now[:danger] = t("users.create.failure")
      render :new, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :gender, :age_group, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/oauths_helper.rb
module OauthsHelper
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/profiles/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 col-lg-8 mx-auto my-5 py-4">
      <%= form_with model: @user, url: profile_path, local: true do |f| %>
        <%= render "shared/error_messages", object: f.object %>
        <div class="mb-3">
          <%= f.label :email, class: "form-label" %>
          <%= f.email_field :email, class: "form-control" %>
        </div>
        <div class="mb-3">
          <%= f.label :password, class: "form-label" %>(8文字以上)
          <%= f.password_field :password, class: "form-control" %>
        </div>
        <div class="mb-3">
          <%= f.label :password_confirmation, class: "form-label" %>
          <%= f.password_field :password_confirmation, class: "form-control" %>
        </div>
        <div class="mb-3">
          <div class="row">
            <div class="col-sm-6 mb-5">
              <%= f.label :gender, class: "form-label" %>
              <%= f.select :gender, User.genders.keys.map { |gender| [I18n.t("activerecord.enums.user.gender.#{gender}"), gender] }, { include_blank: "選択してください" }, class: "form-control" %>            </div>
            <div class="col-sm-6 mb-3">
              <%= f.label :age_group, class: "form-label" %>
              <%= f.select :age_group, User.age_groups.keys.map { |age_group| [I18n.t("activerecord.enums.user.age_group.#{age_group}"), age_group] }, { include_blank: "選択してください" }, class: "form-control" %>
            </div>
          </div>
        </div>
        <div class="mb-5 text-center">
          <%= f.submit "更新", class: "btn btn-primary btn-lg" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/profiles/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 col-lg-8 mx-auto my-5 py-4">
      <table class="table">
        <tr>
          <th scope="row"><%= User.human_attribute_name(:email) %></th>
          <td><%= current_user.email %></td>
        </tr>
        <tr>
          <th scope="row"><%= User.human_attribute_name(:password) %></th>
          <td>--------</td>
        </tr>
        <tr>
        <th scope="row"><%= User.human_attribute_name(:gender) %></th>
          <td><%= current_user.gender_i18n %></td>
        </tr>
        <tr>
          <th scope="row"><%= User.human_attribute_name(:age_group) %></th>
          <td><%= current_user.age_group %></td>
        </tr>
      </table>
      <div class="pt-3 text-center">
        <%= link_to "編集", edit_profile_path, class: "btn btn-primary btn-lg" %>
      </div>
    </div>
  </div>
</div>