config/routes.rb
Rails.application.routes.draw do
  get "oauths/oauth"
  get "oauths/callback"
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  get "plans/destroy"
  root "static_pages#top"
  resources :users, only: %i[new create]
  resources :books, only: %i[index new create show edit update destroy] do
    resources :plans, only: %i[destroy]
    collection do
      get :bookmarks
    end
  end
  resources :bookmarks, only: %i[create destroy]
  resource :profile, only: %i[show edit update]
  resources :password_resets, only: %i[new create edit update]
  resources :contacts, only: %i[new create]

  get "login", to: "user_sessions#new"
  post "login", to: "user_sessions#create"
  delete "logout", to: "user_sessions#destroy"
  get "created_book", to: "books#created_index"
  get "terms", to: "static_pages#terms"
  get "privacy", to: "static_pages#privacy"
  post "oauth/callback", to: "oauths#callback"
  get "oauth/callback", to: "oauths#callback"
  get "oauth/:provider", to: "oauths#oauth", as: :auth_at_provider
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  has_many :books, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :bookmark_books, through: :bookmarks, source: :book
  has_many :authentications, dependent: :destroy
  accepts_nested_attributes_for :authentications

  validates :password, length: { minimum: 8 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }
  validates :email, presence: true, uniqueness: true
  validates :reset_password_token, uniqueness: true, allow_nil: true

  enum gender: { male: 0, female: 1, other: 2 }
  enum age_group: { under19: 0, twenties: 1, thirties: 2, fourties: 3, fifties: 4, over60: 5 }

  def own?(object)
    self.id == object.user_id
  end

  def bookmark(book)
    bookmark_books << book
  end

  def unbookmark(book)
    bookmark_books.destroy(book)
  end

  def bookmark?(book)
    bookmark_books.include?(book)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: %i[new create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      auto_login(@user)
      redirect_to root_path, success: t("users.create.success")
    else
      flash.now[:danger] = t("users.create.failure")
      render :new, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :gender, :age_group, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<div class="container pb-5">
  <div class="row">
    <div class="col-md-10 col-lg-8 mx-auto my-5 py-4">
      <p class="text-danger">
        *は必須項目です
      </p>
      <%= form_with model: @user do |f| %>
        <%= render "shared/error_messages", object: f.object %>
        <div class="mb-3">
          <%= f.label :email, class: "form-label" %>*
          <%= f.email_field :email, class: "form-control" %>
        </div>
        <div class="mb-3">
          <%= f.label :password, class: "form-label" %>*(8文字以上)
          <%= f.password_field :password, class: "form-control" %>
        </div>
        <div class="mb-3">
          <%= f.label :password_confirmation, class: "form-label" %>*
          <%= f.password_field :password_confirmation, class: "form-control" %>
        </div>
        <div class="mb-3">
          <div class="row">
            <div class="col-sm-6 mb-5">
              <%= f.label :gender, class: "form-label" %>
              <%= f.select :gender, User.genders.keys.map { |gender| [I18n.t("activerecord.enums.user.gender.#{gender}"), gender] }, { include_blank: "選択してください" }, class: "form-control" %>
            </div>
            <div class="col-sm-6 mb-3">
              <%= f.label :age_group, class: "form-label" %>
              <%= f.select :age_group, User.age_groups.keys.map { |age_group| [I18n.t("activerecord.enums.user.age_group.#{age_group}"), age_group] }, { include_blank: "選択してください" }, class: "form-control" %>
            </div>
          </div>
        </div>
        <div class="mb-1 text-center">
          <%= f.submit "登録", class: "btn btn-primary btn-lg" %>
        </div>
      <% end %>
      <div class="mb-3 text-center">
        <%= image_tag "LINE_btn_base.png", size: "20x20" %>
        <%= link_to 'LINEで登録', auth_at_provider_path(provider: :line) %>
      </div>

      <div class="text-center mb-3">
        <%= link_to t("users.new.to_login_page"), login_path %>
      </div>
    </div>
  </div>
</div>