config/routes.rb
Rails.application.routes.draw do
  get "oauths/oauth"
  get "oauths/callback"
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  get "plans/destroy"
  root "static_pages#top"
  resources :users, only: %i[new create]
  resources :books, only: %i[index new create show edit update destroy] do
    resources :plans, only: %i[destroy]
    collection do
      get :bookmarks
    end
  end
  resources :bookmarks, only: %i[create destroy]
  resource :profile, only: %i[show edit update]
  resources :password_resets, only: %i[new create edit update]
  resources :contacts, only: %i[new create]

  get "login", to: "user_sessions#new"
  post "login", to: "user_sessions#create"
  delete "logout", to: "user_sessions#destroy"
  get "created_book", to: "books#created_index"
  get "terms", to: "static_pages#terms"
  get "privacy", to: "static_pages#privacy"
  post "oauth/callback", to: "oauths#callback"
  get "oauth/callback", to: "oauths#callback"
  get "oauth/:provider", to: "oauths#oauth", as: :auth_at_provider
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/authentication.rb
class Authentication < ApplicationRecord
  belongs_to :user
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true, length: { maximum: 255 }
  validates :outline_title, length: { maximum: 255 }
  validates :outline_body, length: { maximum: 65_535 }
  validates :is_public, inclusion: { in: [ true, false ] }

  belongs_to :user
  has_many :plans, dependent: :destroy
  has_many :bookmarks, dependent: :destroy

  accepts_nested_attributes_for :plans, allow_destroy: true

  BACKGROUND_IMAGES = %w[blue.jpg brown.jpg green.jpg orange.jpg pink.jpg purple.jpg red.jpg yellow.jpg].freeze

  validates :image, inclusion: { in: BACKGROUND_IMAGES }
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :user_id, uniqueness: { scope: :book_id }
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :email, presence: true
  validates :message, presence: true
end

app/models/plan.rb
class Plan < ApplicationRecord
  validates :title, length: { maximum: 255 }
  validates :location, length: { maximum: 255 }
  validates :detail, length: { maximum: 65_535 }
  validates :memo, length: { maximum: 65_535 }
  validates :cost_display_per, inclusion: { in: [ true, false ] }, allow_nil: true
  validates :cost_display_total, inclusion: { in: [ true, false ] }, allow_nil: true

  belongs_to :book
  geocoded_by :location
  after_validation :geocode
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  has_many :books, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :bookmark_books, through: :bookmarks, source: :book
  has_many :authentications, dependent: :destroy
  accepts_nested_attributes_for :authentications

  validates :password, length: { minimum: 8 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }
  validates :email, presence: true, uniqueness: true
  validates :reset_password_token, uniqueness: true, allow_nil: true

  enum gender: { male: 0, female: 1, other: 2 }
  enum age_group: { under19: 0, twenties: 1, thirties: 2, fourties: 3, fifties: 4, over60: 5 }

  def own?(object)
    self.id == object.user_id
  end

  def bookmark(book)
    bookmark_books << book
  end

  def unbookmark(book)
    bookmark_books.destroy(book)
  end

  def bookmark?(book)
    bookmark_books.include?(book)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  skip_before_action :require_login, only: %i[index show]

  def index
    @books = Book.where(is_public: true).page(params[:page]).per(15)
  end

  def new
    @book = Book.new
  end

  def create
    @book = current_user.books.build(book_params)
    if @book.save
      redirect_to book_path(@book), success: t("books.create.success")
    else
      flash.now[:danger] = t("books.create.failure")
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @book = Book.find(params[:id])
    @plans = Plan.find_by(book_id: params[:id])
  end

  def edit
    @book = current_user.books.find(params[:id])
  end

  def update
    @book = current_user.books.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), success: t("books.update.success")
    else
      flash.now[:danger] = t("books.update.failure")
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    book = current_user.books.find(params[:id])
    book.destroy!
    redirect_to books_path, success: t("books.destroy.success"), status: :see_other
  end

  def created_index
    @books = Book.where(user_id: current_user.id).page(params[:page]).per(15)
  end

  def bookmarks
    @bookmark_books = current_user.bookmark_books.includes(:user)
  end

  private

  def book_params
    params.require(:book).permit(
      :title, :outline_title, :outline_body, :is_public, :image,
      plans_attributes: [ :id, :date, :title, :start_time, :end_time, :icon, :location, :location_url, :detail, :memo, :cost, :cost_display_per, :cost_display_total, :_destroy, :latitude, :longitude ]
      )
  end
end

app/controllers/oauths_controller.rb
class OauthsController < ApplicationController
  skip_before_action :require_login

  def oauth
    login_at(auth_params[:provider])
  end

  def callback
    provider = auth_params[:provider]
    status = auth_params[:status]
    Rails.logger.debug "#{status}"
    if @user = login_from(provider)
      redirect_to root_path, notice: "#{provider.titleize}でログインしました"
    else
      begin
        @user = create_from(provider)
        reset_session
        auto_login(@user)
        redirect_to root_path, notice: "#{provider.titleize}でログインしました"
      rescue
        # flash.now[:danger] = "#{provider.titleize}でログインできませんでした"
        # render :new, status: :unprocessable_entity
        redirect_to root_path, notice: "#{provider.titleize}でログインできませんでした"
      end
    end
  end

  private

  def auth_params
    params.permit(:code, :provider, :error, :state)
  end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action :set_book

  def destroy
    @plan = @book.plans.find(params[:id])
    @plan.destroy
    redirect_to edit_book_path(@book)
  end

  private

  def set_book
    @book = current_user.books.find(params[:book_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: %i[new create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      auto_login(@user)
      redirect_to root_path, success: t("users.create.success")
    else
      flash.now[:danger] = t("users.create.failure")
      render :new, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :gender, :age_group, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/oauths_helper.rb
module OauthsHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "私のしおり" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta property="og:title" content="私のしおり">
    <meta property="og:type" content="website">
    <meta property="og:description" content="私のしおりは、旅行しおり作成サービスです">
    <meta property="og:url" content="https://watashi-no-shiori.com/">
    <meta property="og:site_name" content="私のしおり">
    <meta property="og:image" content="">
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:title" content="私のしおり">
    <meta name="twitter:description" content="私のしおりは、旅行しおり作成サービスです">
    <meta name="twitter:image" content="<%= asset_path('ogp_image.png') %>"

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="icon" href="<%= asset_path('favicon.ico') %>" type="image/x-icon">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
    <script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV["API_KEY"] %>&callback=initMap&libraries=places" async defer></script>
  </head>

  <body>
    <% if logged_in? %>
      <%= render "shared/header" %>
    <% else %>
      <%= render "shared/before_login_header" %>
    <% end %>
    <%= render "shared/flash_message" %>
    <%= yield %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/shared/_before_login_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <%= link_to "私のしおり", "/", class: "navbar-brand ms-2" %>
    <button class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto main-nav align-items-center mx-2">
        <li class="nav-item">
          <%= link_to t("header.new_user"), new_user_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to t("header.login"), login_path, class: "nav-link" %>
        </li>
      </ul>
    </div>
</header>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <ul class="mb-0">
      <% object.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>">
    <%= message %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="bg-primary footer fixed-bottom">
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="collapse navbar-collapse justify-content-md-center">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "利用規約", terms_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "プライバシーポリシー", privacy_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "お問い合わせ", new_contact_path, class: "nav-link" %>
        </li>
      </ul>
    </div>
  </nav>
  <div class='mx-2 text-white text-end'>
    <p>Copyright ©私のしおり All Rights Reserved.</p>
  </div>
</footer>

app/views/shared/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <%= link_to "私のしおり", "/", class: "navbar-brand ms-2" %>
    <button class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto main-nav align-items-center mx-2">
        <li class="nav-item">
          <%= link_to t("header.create_book"), new_book_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to t("header.book_index"), books_path, class: "nav-link" %>
        </li>
        <li class='nav-item dropdown dropdown-slide' >
          <%= link_to 'マイページ', "#", class: 'nav-link', data: { bs_toggle: 'dropdown' }, aria: { haspopup: 'true', expanded: 'false' } %>
          <div class='dropdown-menu dropdown-menu-end'>
          <div class='dropdown-item'>
            <%= link_to "作成しおり一覧", created_book_path, class: 'dropdown-item' %>
          </div>
          <div class='dropdown-item'>
            <%= link_to "ブックマーク一覧", bookmarks_books_path, class: 'dropdown-item' %>
          </div>
          <div class='dropdown-item'>
            <%= link_to "登録情報", profile_path, class: 'dropdown-item' %>
          </div>
          <div class='dropdown-item'>
            <%= link_to t("header.logout"), logout_path, class: "dropdown-item", data: { turbo_method: :delete } %>
          </div>
        </li>
      </ul>
    </div>
</header>