config/routes.rb
Rails.application.routes.draw do
  get "oauths/oauth"
  get "oauths/callback"
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  get "plans/destroy"
  root "static_pages#top"
  resources :users, only: %i[new create]
  resources :books, only: %i[index new create show edit update destroy] do
    resources :plans, only: %i[destroy]
    collection do
      get :bookmarks
    end
  end
  resources :bookmarks, only: %i[create destroy]
  resource :profile, only: %i[show edit update]
  resources :password_resets, only: %i[new create edit update]
  resources :contacts, only: %i[new create]

  get "login", to: "user_sessions#new"
  post "login", to: "user_sessions#create"
  delete "logout", to: "user_sessions#destroy"
  get "created_book", to: "books#created_index"
  get "terms", to: "static_pages#terms"
  get "privacy", to: "static_pages#privacy"
  post "oauth/callback", to: "oauths#callback"
  get "oauth/callback", to: "oauths#callback"
  get "oauth/:provider", to: "oauths#oauth", as: :auth_at_provider
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/authentication.rb
class Authentication < ApplicationRecord
  belongs_to :user
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true, length: { maximum: 255 }
  validates :outline_title, length: { maximum: 255 }
  validates :outline_body, length: { maximum: 65_535 }
  validates :is_public, inclusion: { in: [ true, false ] }

  belongs_to :user
  has_many :plans, dependent: :destroy
  has_many :bookmarks, dependent: :destroy

  accepts_nested_attributes_for :plans, allow_destroy: true

  BACKGROUND_IMAGES = %w[blue.jpg brown.jpg green.jpg orange.jpg pink.jpg purple.jpg red.jpg yellow.jpg].freeze

  validates :image, inclusion: { in: BACKGROUND_IMAGES }
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :user_id, uniqueness: { scope: :book_id }
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :email, presence: true
  validates :message, presence: true
end

app/models/plan.rb
class Plan < ApplicationRecord
  validates :title, length: { maximum: 255 }
  validates :location, length: { maximum: 255 }
  validates :detail, length: { maximum: 65_535 }
  validates :memo, length: { maximum: 65_535 }
  validates :cost_display_per, inclusion: { in: [ true, false ] }, allow_nil: true
  validates :cost_display_total, inclusion: { in: [ true, false ] }, allow_nil: true

  belongs_to :book
  geocoded_by :location
  after_validation :geocode
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  has_many :books, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :bookmark_books, through: :bookmarks, source: :book
  has_many :authentications, dependent: :destroy
  accepts_nested_attributes_for :authentications

  validates :password, length: { minimum: 8 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }
  validates :email, presence: true, uniqueness: true
  validates :reset_password_token, uniqueness: true, allow_nil: true

  enum gender: { male: 0, female: 1, other: 2 }
  enum age_group: { under19: 0, twenties: 1, thirties: 2, fourties: 3, fifties: 4, over60: 5 }

  def own?(object)
    self.id == object.user_id
  end

  def bookmark(book)
    bookmark_books << book
  end

  def unbookmark(book)
    bookmark_books.destroy(book)
  end

  def bookmark?(book)
    bookmark_books.include?(book)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  skip_before_action :require_login, only: %i[index show]

  def index
    @books = Book.where(is_public: true).page(params[:page]).per(15)
  end

  def new
    @book = Book.new
  end

  def create
    @book = current_user.books.build(book_params)
    if @book.save
      redirect_to book_path(@book), success: t("books.create.success")
    else
      flash.now[:danger] = t("books.create.failure")
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @book = Book.find(params[:id])
    @plans = Plan.find_by(book_id: params[:id])
  end

  def edit
    @book = current_user.books.find(params[:id])
  end

  def update
    @book = current_user.books.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), success: t("books.update.success")
    else
      flash.now[:danger] = t("books.update.failure")
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    book = current_user.books.find(params[:id])
    book.destroy!
    redirect_to books_path, success: t("books.destroy.success"), status: :see_other
  end

  def created_index
    @books = Book.where(user_id: current_user.id).page(params[:page]).per(15)
  end

  def bookmarks
    @bookmark_books = current_user.bookmark_books.includes(:user)
  end

  private

  def book_params
    params.require(:book).permit(
      :title, :outline_title, :outline_body, :is_public, :image,
      plans_attributes: [ :id, :date, :title, :start_time, :end_time, :icon, :location, :location_url, :detail, :memo, :cost, :cost_display_per, :cost_display_total, :_destroy, :latitude, :longitude ]
      )
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  skip_before_action :require_login, only: %i[new create]

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      ContactMailer.contact_mail(@contact).deliver
      redirect_to root_path, success: "お問い合わせ内容を送信しました"
    else
      flash.now[:danger] = "お問い合わせ内容を送信できませんでした"
      render :new, status: :unprocessable_entity
    end
  end

  private

  def contact_params
    params.require(:contact).permit(:email, :message)
  end
end

app/controllers/oauths_controller.rb
class OauthsController < ApplicationController
  skip_before_action :require_login

  def oauth
    login_at(auth_params[:provider])
  end

  def callback
    provider = auth_params[:provider]
    status = auth_params[:status]
    Rails.logger.debug "#{status}"
    if @user = login_from(provider)
      redirect_to root_path, notice: "#{provider.titleize}でログインしました"
    else
      begin
        @user = create_from(provider)
        reset_session
        auto_login(@user)
        redirect_to root_path, notice: "#{provider.titleize}でログインしました"
      rescue
        # flash.now[:danger] = "#{provider.titleize}でログインできませんでした"
        # render :new, status: :unprocessable_entity
        redirect_to root_path, notice: "#{provider.titleize}でログインできませんでした"
      end
    end
  end

  private

  def auth_params
    params.permit(:code, :provider, :error, :state)
  end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action :set_book

  def destroy
    @plan = @book.plans.find(params[:id])
    @plan.destroy
    redirect_to edit_book_path(@book)
  end

  private

  def set_book
    @book = current_user.books.find(params[:book_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: %i[new create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      auto_login(@user)
      redirect_to root_path, success: t("users.create.success")
    else
      flash.now[:danger] = t("users.create.failure")
      render :new, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :gender, :age_group, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/oauths_helper.rb
module OauthsHelper
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_book.html.erb
<% books.each do |book| %>
  <div class="col-md-6 col-lg-4 mb-3">
    <div id="book-id-<%= book.id %>">
      <div class="card">
        <%= image_tag image_path("backgrounds/#{book.image.presence || 'blue.jpg'}"), class: "card-img-top", width: "300", height: "200" %>
        <div class="card-img-overlay d-flex justify-content-end z-1">
	        <% if logged_in? %>
            <% unless current_user.own?(book) %>
              <% if current_user.bookmark?(book) %>
                <%= render 'unbookmark', { book: book } %>
              <% else %>
                <%= render 'bookmark', { book: book } %>
              <% end %>
            <% end %>
          <% end %>
	      </div>
        <div class="card-body z-2">
          <div class="d-flex justify-content-end">
            <h4 class="card-title">
              <%= link_to book.title, book_path(book) %>
            </h4>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/books/_bookmark.html.erb
<%= link_to bookmarks_path(book_id: book.id), id: "bookmark-button-for-book-#{book.id}", data: { turbo_method: :post } do %>
  <i class="bi bi-bookmark"></i>
<% end %>

app/views/books/_unbookmark.html.erb
<%= link_to bookmark_path(current_user.bookmarks.find_by(book_id: book.id)), id: "unbookmark-button-for-book-#{book.id}", data: { turbo_method: :delete } do %>
  <i class="bi bi-bookmark-fill"></i>
<% end %>

app/views/books/bookmarks.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 mx-auto my-5 pt-4">
      <div class="row" >
        <% if @bookmark_books.present? %>
           <%= render 'book', { books: @bookmark_books } %>
        <% else %>
          <div class="mb-3 text-center">
            ブックマークしているしおりはありません
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/books/created_index.html.erb
<div class="container pb-5">
  <div class="row">
    <div class="col-12 mx-auto my-5 pt-4">
      <div class="row" >
        <% if @books.present? %>
          <%= render 'book', {books: @books} %>
        <% else %>
          <div class="mb-3 text-center">
            作成したしおりはありません
          </div>
        <% end %>
        <%= paginate @books, theme: 'bootstrap-5' %>
      </div>
    </div>
  </div>
</div>

app/views/books/edit.html.erb
<div class="container mb-5 pb-5">
<div class="row">
  <div class="col-md-10 col-lg-8 mx-auto my-5 py-4">
    <%= form_with model: @book do |f| %>
      <%= render "shared/error_messages", object: f.object %>
      <div class="pb-3">
        <div class="mb-3">
          <%= f.label :title %>
          <%= f.text_field :title, class: "form-control" %>
        </div>
        <div class="mb-3">
          <%= f.label :outline_title %>
          <%= f.text_field :outline_title, class: "form-control" %>
        </div>
        <div class="mb-4">
          <%= f.label :outline_body %>
          <%= f.text_area :outline_body, class: "form-control" %>
        </div>
        <div class="mb-4">
          <%= f.label :image, "背景を選択" %>
          <%= f.select :image, options_for_select(Book::BACKGROUND_IMAGES, @book.image), class: "form-select" %>
        </div>
      </div>
      <div class="row">
        <%= f.fields_for :plans do |plan_form| %>
          <div class="plan plan-form mb-3 px-2 py-2 border border-primary-subtle" data-id="<%= plan_form.object.id %>">
            <%= plan_form.hidden_field :id, value: plan_form.object.new_record? ? nil : plan_form.object.id %>
            <p>プラン<%= plan_form.object.id %></p>
            <div class="row">
              <div class="col-md-3 mb-3">
                <%= plan_form.date_field :date, class: "form-control" %>
              </div>
                <div class="col-md-9 mb-3">
                  <%= plan_form.text_field :title, class: "form-control", placeholder: "タイトル" %>
              </div>
            </div>
            <div class="row">
              <div class="col-md-3 mb-3">
                <%= plan_form.time_field :start_time, class: "form-control" %>
              </div>
              <div class="col-md-9 mb-3">
                <%= plan_form.text_field :location, id: "location", class: "form-control", placeholder: "場所" %>
              </div>
            </div>
            <div class="row">
              <div class="col-md-1 mb-3 text-end">
                ～
              </div>
              <div class="col-md-2 mb-3">
                <%= plan_form.time_field :end_time, class: "form-control" %>
              </div>
              <div class="col-md-9 mb-3">
                <%= plan_form.text_area :detail, class: "form-control", placeholder: "詳細" %>
              </div>
            </div>
            <div class="row d-flex justify-content-end">
              <div class="col-md-9 mb-3">
                <%= plan_form.text_area :memo, class: "form-control", placeholder: "メモ（公開されません）" %>
              </div>
            </div>
          </div>
        <% end %>

        <div id="add-container"></div>

        <div class="d-grid gap-2 mb-5">
          <button class="btn btn-primary" id="add-plan-button" type="button">
            プラン追加
          </button>
        </div>
      </div>

      <div class="mb-2 text-center">
      <%= f.check_box :is_public  %>
      <%= f.label :is_public, "公開する" %>
    </div>

      <div class=" mb-2 text-center">
        <%= f.submit "更新", class: "btn btn-primary btn-lg" %>
      </div>
    <% end %>
  </div>
</div>
</div>

app/views/books/index.html.erb
<div class="container pb-5">
  <div class="row">
    <div class="col-12 mx-auto my-5 pt-4 ">
      <div class="row" >
        <% if @books.present? %>
          <%= render 'book', {books: @books} %>
        <% else %>
          <div class="mb-3 text-center">
            しおりがありません
          </div>
        <% end %>
        <%= paginate @books, theme: 'bootstrap-5' %>
      </div>
    </div>
  </div>
</div> 

app/views/books/new.html.erb
 <div class="container pb-5">
  <div class="row">
    <div class="col-md-10 col-lg-8 mx-auto my-5 py-4">
      <%= form_with model: @book, class: "new_book" do |f| %>
        <%= render "shared/error_messages", object: f.object %>
        <div class="pb-3">
          <div class="mb-3">
            <%= f.label :title %>
            <%= f.text_field :title, class: "form-control" %>
          </div>
          <div class="mb-3">
            <%= f.label :outline_title %>
            <%= f.text_field :outline_title, class: "form-control" %>
          </div>
          <div class="mb-3">
            <%= f.label :outline_body %>
            <%= f.text_area :outline_body, class: "form-control" %>
          </div>
          <div class="mb-4">
            <%= f.label :image, "背景を選択" %>
            <%= f.select :image, options_for_select(Book::BACKGROUND_IMAGES), class: "form-select" %>
          </div>
        </div>
        <div class="row">
          <%= f.fields_for :plans do |plan_form| %>
            <div class="plan mb-3 px-2 py-2 border border-primary-subtle sortable-handle">
              <div class="row">
                <div class="col-md-3 mb-3">
                  <%= plan_form.date_field :date, class: "form-control" %>
                </div>
	              <div class="col-md-9 mb-3">
	                <%= plan_form.text_field :title, class: "form-control", placeholder: "タイトル" %>
                </div>
              </div>
              <div class="row">
                <div class="col-md-3 mb-3">
                  <%= plan_form.time_field :start_time, class: "form-control" %>
                </div>
	              <div class="col-md-9 mb-3">
	                <%= plan_form.text_field :location, id: "location", class: "form-control", placeholder: "場所" %>
                </div>
              </div>
              <div class="row">
                <div class="col-md-1 mb-3 text-end">
                  ～
                </div>
                <div class="col-md-3 mb-3">
                  ~<%= plan_form.time_field :end_time, class: "form-control" %>
                </div>
	              <div class="col-md-9 mb-3">
	                <%= plan_form.text_area :detail, class: "form-control", placeholder: "詳細" %>
                </div>
              </div>
              <div class="row d-flex justify-content-end">
	              <div class="col-md-9 mb-3">
	                <%= plan_form.text_area :memo, class: "form-control", placeholder: "メモ（公開されません）" %>
                </div>
              </div>
              <div class="text-end">
                <%= link_to plan_path(plan_form.object), data: { turbo_method: :delete, turbo_confirm: "このプランを削除しますか？" } do %>
                <i class="bi bi-trash-fill icon-lg"></i>
              </div>
            <% end %>
      </div>
	          </div>
          <% end %>

          <div id="add-container"></div>

          <div class="d-grid gap-2 mb-5">
            <button class="btn btn-primary" id="add-plan-button" type="button">
              プラン追加
            </button>
          </div>
        </div>

        <div class="mb-2 text-center">
          <%= f.check_box :is_public, checked: false %>
          <%= f.label :is_public, "公開する" %>
        </div>

        <div class=" mb-4 text-center">
          <%= f.submit "登録", class: "btn btn-primary btn-lg" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container mb-5 pb-5">
  <div class="row">
    <div class="col-10 mx-auto my-5 py-4">
      <div class="card">
        <%= image_tag image_path("backgrounds/#{@book.image.presence || 'blue.jpg'}"), class: "card-img-top", height: "600" %>
        <div class="card-img-overlay d-flex flex-column">
          <div class="my-3 text-center display-1 mx-auto my-auto">
            <%= @book.title %>
          </div>
          <div class="col-8 fs-4 mx-auto">
            <%= @book.outline_title %>
            <br>
            <%= @book.outline_body %>
          </div>
          <div class="container pe-3 pb-3 text-end mt-auto ms-auto">
            <% if logged_in? %>
              <% if current_user.own?(@book) %>
                <div class="ms-auto">
                  <%= link_to edit_book_path(@book), id: "button-edit-#{@book.id}" do %>
                    <i class="bi bi-pencil-fill icon-lg"></i>
                  <% end %>
                  <%= link_to book_path(@book), id: "button-delete-#{@book.id}", data: { turbo_method: :delete, turbo_confirm: t("books.show.delete_confirm") } do %>
                    <i class="bi bi-trash-fill icon-lg"></i>
                  <% end %>
                </div>
              <% end %>
            <% end %>
          </div>
          </div>
        </div>
      </div>

      <div id="book-plan">
        <div class="row">
          <div class="col-9 mt-5 mx-auto">
            <% @book.plans.each do |plan| %>
              <div class="row mb-3">
                <div class="col-10 mb-3">
                  <h4><%= plan.date.strftime("%Y/%m/%d") if plan.date.present? %></h4>
                </div>
                <div class="col-md-9">
                  <div class="row">
                    <div class="col-md-3 fs-4">
                      <%= plan.start_time.strftime("%H:%M") if plan.start_time.present? %>
                    </div>
                    <div class="col-md-9 fs-4">
                      <%= plan.title if plan.title.present? %>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-md-3 mb-2 fs-5">
                      <%= plan.end_time.strftime("~ %H:%M") if plan.end_time.present? %>
                    </div>
                    <div class="col-md-9 mb-2 fs-5">
                      <%= plan.location if plan.location.present? %>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-md-9 mb-3 offset-md-3 fs-5">
                      <%= plan.detail if plan.detail.present? %>
                    </div>
                    <% if logged_in? && @book.user_id == current_user.id %>
                      <div class="col-md-9 mb-3 offset-md-3 fs-5">
                        <%= plan.memo if plan.memo.present? %>
                      </div>
                    <% end %>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>

      <div class="mb-5 pb-5 d-flex justify-content-center">
        <div id="map" style="height: 600px; width: 70%;"></div>
      </div>
    </div>
  </div>
</div>

<script>
document.addEventListener("turbo:load", function() {
  loadGoogleMapsAPI(() => {
    initializeMap();
  });
});

function loadGoogleMapsAPI(callback) {
  if (window.google && window.google.maps) {
    callback();
  } else {
    window.initMapCallback = callback;
    const script = document.createElement('script');
    script.src = `https://maps.googleapis.com/maps/api/js?key=<%= ENV["API_KEY"] %>&libraries=places&callback=initMapCallback`;
    script.async = true;
    script.defer = true;
    document.body.appendChild(script);
  }
}

document.addEventListener("turbo:before-cache", function() {
  const mapElement = document.getElementById('map');
  if (mapElement) {
    mapElement.innerHTML = "";
  }
});

function initializeMap() {
  const mapElement = document.getElementById('map');
  if (!mapElement) {
    console.error('Map element not found');
    return;
  }

  const mapOptions = {
    center: { lat: 35.6803997, lng: 139.7690174 },
    zoom: 10
  };
  const map = new google.maps.Map(mapElement, mapOptions);
  const plans = <%= raw @book.plans.to_json %>;

  // マーカーを管理する配列
  let markers = [];

  plans.forEach(plan => {
  // locationがnilの場合、latitudeとlongitudeをリセットする
    if (!plan.location) {
      plan.latitude = null;
      plan.longitude = null;
    }

    if (plan.latitude && plan.longitude) {
      // 既にマーカーがある場合は削除
      const existingMarker = markers.find(marker => marker.planId === plan.id);
      if (existingMarker) {
        existingMarker.setMap(null);  // マーカーを地図から削除
      }

      // 新しいマーカーを作成
      const marker = new google.maps.Marker({
        position: { lat: plan.latitude, lng: plan.longitude },
        map: map,
      })

      // マーカーにプランIDを付加
      marker.planId = plan.id;

      // マーカーを配列に追加
      markers.push(marker);
    }
  });
}
</script>

app/views/oauths/callback.html.erb
<h1>Oauths#callback</h1>
<p>Find me in app/views/oauths/callback.html.erb</p>

app/views/oauths/oauth.html.erb
<h1>Oauths#oauth</h1>
<p>Find me in app/views/oauths/oauth.html.erb</p>